partido([[bournemouth,arsenal],3,viernes,18]).
partido([[wolves,chelsea],7,sabado,19]).
partido([[brighton,west_ham],17,domingo,21]).
partido([[everton,bournemouth],15,sabado,22]).
partido([[leicester_city,southampton],8,sabado,21]).
partido([[wolves,crystal_palace],16,sabado,19]).
partido([[wolves,west_ham],2,viernes,15]).
partido([[brighton,crystal_palace],14,domingo,22]).
partido([[bournemouth,man_united],12,sabado,18]).
partido([[brighton,aston_villa],12,domingo,20]).
partido([[chelsea,fulham],12,domingo,18]).
partido([[nottm_forest,leicester_city],12,sabado,16]).
partido([[crystal_palace,aston_villa],18,sabado,16]).
partido([[west_ham,nottm_forest],18,domingo,15]).
partido([[brighton,chelsea],18,domingo,22]).
partido([[leicester_city,man_united],18,viernes,21]).
partido([[bournemouth,brentford],18,sabado,21]).
partido([[everton,leeds_united],18,viernes,16]).
partido([[southampton,man_city],18,domingo,20]).
partido([[liverpool,newcastle],18,sabado,20]).
partido([[tottenham,fulham],18,viernes,15]).
partido([[arsenal,wolves],18,sabado,19]).
partido([[newcastle,southampton],12,sabado,19]).
partido([[wolves,liverpool],12,domingo,19]).
partido([[tottenham,arsenal],12,sabado,21]).
partido([[leeds_united,man_city],12,domingo,14]).
partido([[fulham,man_city],14,domingo,20]).
partido([[man_city,bournemouth],9,domingo,22]).
partido([[arsenal,chelsea],14,viernes,14]).
partido([[bournemouth,nottm_forest],14,sabado,19]).
partido([[wolves,man_united],14,sabado,20]).
partido([[brentford,newcastle],14,domingo,20]).
partido([[west_ham,aston_villa],14,sabado,16]).
partido([[everton,liverpool],14,sabado,21]).
partido([[leicester_city,tottenham],14,sabado,21]).
partido([[southampton,leeds_united],14,domingo,16]).
partido([[west_ham,leeds_united],6,viernes,17]).
partido([[leicester_city,liverpool],6,viernes,22]).
partido([[fulham,newcastle],6,domingo,20]).
partido([[arsenal,brentford],6,domingo,18]).
partido([[wolves,brighton],6,sabado,17]).
partido([[man_city,nottm_forest],6,sabado,15]).
partido([[aston_villa,tottenham],6,sabado,14]).
partido([[man_united,crystal_palace],6,domingo,19]).
partido([[bournemouth,chelsea],6,domingo,16]).
partido([[everton,southampton],6,viernes,15]).
partido([[newcastle,crystal_palace],2,viernes,16]).
partido([[fulham,aston_villa],2,viernes,22]).
partido([[tottenham,brighton],2,sabado,14]).
partido([[arsenal,leeds_united],2,domingo,20]).
partido([[man_united,man_city],2,viernes,20]).
partido([[liverpool,brentford],2,sabado,15]).
partido([[chelsea,southampton],2,sabado,18]).
partido([[nottm_forest,everton],2,domingo,15]).
partido([[leicester_city,bournemouth],2,domingo,22]).
partido([[tottenham,chelsea],11,sabado,19]).
partido([[man_united,brighton],11,domingo,19]).
partido([[leicester_city,fulham],11,sabado,16]).
partido([[leeds_united,bournemouth],11,viernes,14]).
partido([[newcastle,west_ham],11,sabado,19]).
partido([[nottm_forest,crystal_palace],11,domingo,18]).
partido([[aston_villa,brentford],11,viernes,16]).
partido([[arsenal,everton],11,domingo,14]).
partido([[wolves,southampton],11,viernes,15]).
partido([[liverpool,man_city],11,sabado,22]).
partido([[liverpool,chelsea],5,domingo,16]).
partido([[crystal_palace,bournemouth],1,domingo,20]).
partido([[man_city,arsenal],19,domingo,20]).
partido([[southampton,brighton],19,domingo,16]).
partido([[leicester_city,west_ham],19,viernes,14]).
partido([[crystal_palace,liverpool],19,sabado,16]).
partido([[bournemouth,aston_villa],19,domingo,22]).
partido([[brentford,wolves],19,sabado,20]).
partido([[leeds_united,chelsea],19,domingo,18]).
partido([[fulham,everton],19,sabado,21]).
partido([[man_united,tottenham],19,domingo,17]).
partido([[nottm_forest,newcastle],19,sabado,14]).
partido([[arsenal,crystal_palace],5,viernes,18]).
partido([[crystal_palace,chelsea],8,sabado,17]).
partido([[arsenal,liverpool],8,viernes,22]).
partido([[bournemouth,brighton],16,sabado,22]).
partido([[west_ham,tottenham],16,domingo,19]).
partido([[nottm_forest,southampton],16,viernes,18]).
partido([[fulham,leeds_united],16,viernes,22]).
partido([[chelsea,brentford],16,sabado,18]).
partido([[everton,man_united],16,viernes,21]).
partido([[aston_villa,liverpool],16,sabado,15]).
partido([[arsenal,leicester_city],16,viernes,19]).
partido([[man_city,newcastle],16,domingo,15]).
partido([[man_united,leeds_united],5,viernes,20]).
partido([[brighton,nottm_forest],5,viernes,21]).
partido([[southampton,brentford],5,sabado,19]).
partido([[west_ham,fulham],5,sabado,22]).
partido([[tottenham,everton],5,domingo,17]).
partido([[leicester_city,man_city],5,domingo,21]).
partido([[wolves,aston_villa],5,viernes,15]).
partido([[bournemouth,newcastle],5,domingo,14]).
partido([[brighton,newcastle],8,viernes,19]).
partido([[bournemouth,tottenham],8,viernes,14]).
partido([[leeds_united,aston_villa],8,domingo,14]).
partido([[fulham,nottm_forest],8,sabado,22]).
partido([[west_ham,man_city],8,domingo,16]).
partido([[man_united,brentford],8,viernes,16]).
partido([[wolves,everton],8,sabado,16]).
partido([[liverpool,brighton],15,viernes,18]).
partido([[newcastle,chelsea],15,sabado,16]).
partido([[wolves,man_city],15,viernes,22]).
partido([[man_united,west_ham],15,domingo,17]).
partido([[crystal_palace,tottenham],15,sabado,18]).
partido([[leicester_city,leeds_united],15,domingo,20]).
partido([[brentford,fulham],15,sabado,17]).
partido([[southampton,aston_villa],15,domingo,22]).
partido([[arsenal,nottm_forest],15,viernes,21]).
partido([[man_city,everton],1,sabado,20]).
partido([[leeds_united,tottenham],4,viernes,17]).
partido([[brentford,nottm_forest],4,sabado,22]).
partido([[crystal_palace,leicester_city],4,domingo,18]).
partido([[everton,chelsea],4,sabado,19]).
partido([[fulham,bournemouth],4,viernes,19]).
partido([[newcastle,wolves],4,domingo,19]).
partido([[arsenal,brighton],4,domingo,18]).
partido([[man_city,aston_villa],4,domingo,18]).
partido([[southampton,west_ham],4,viernes,15]).
partido([[man_united,liverpool],4,domingo,20]).
partido([[liverpool,nottm_forest],17,viernes,21]).
partido([[aston_villa,chelsea],17,sabado,15]).
partido([[tottenham,wolves],17,sabado,14]).
partido([[everton,leicester_city],17,sabado,21]).
partido([[man_city,brentford],17,viernes,20]).
partido([[arsenal,newcastle],17,sabado,16]).
partido([[fulham,man_united],17,domingo,16]).
partido([[southampton,bournemouth],17,viernes,14]).
partido([[leeds_united,crystal_palace],17,viernes,16]).
partido([[arsenal,fulham],1,domingo,17]).
partido([[brighton,brentford],1,viernes,14]).
partido([[leicester_city,wolves],1,sabado,17]).
partido([[newcastle,aston_villa],1,viernes,20]).
partido([[chelsea,west_ham],1,sabado,19]).
partido([[southampton,tottenham],1,viernes,19]).
partido([[liverpool,leeds_united],1,sabado,14]).
partido([[man_united,nottm_forest],1,sabado,18]).
partido([[leicester_city,chelsea],9,domingo,21]).
partido([[aston_villa,arsenal],9,sabado,19]).
partido([[west_ham,liverpool],9,domingo,20]).
partido([[crystal_palace,brentford],9,sabado,21]).
partido([[brighton,everton],9,viernes,22]).
partido([[fulham,wolves],9,sabado,17]).
partido([[leeds_united,nottm_forest],9,sabado,19]).
partido([[southampton,man_united],9,domingo,18]).
partido([[newcastle,tottenham],9,sabado,14]).
partido([[man_united,aston_villa],10,viernes,19]).
partido([[fulham,crystal_palace],10,domingo,19]).
partido([[chelsea,nottm_forest],10,viernes,21]).
partido([[leeds_united,brentford],10,sabado,22]).
partido([[tottenham,liverpool],10,sabado,17]).
partido([[wolves,bournemouth],10,sabado,14]).
partido([[leicester_city,newcastle],10,sabado,18]).
partido([[brighton,man_city],10,sabado,19]).
partido([[west_ham,everton],10,domingo,20]).
partido([[southampton,arsenal],10,sabado,15]).
partido([[leeds_united,brighton],7,sabado,17]).
partido([[liverpool,fulham],7,viernes,21]).
partido([[leicester_city,brentford],7,viernes,14]).
partido([[bournemouth,west_ham],7,viernes,15]).
partido([[southampton,crystal_palace],7,domingo,22]).
partido([[nottm_forest,aston_villa],7,viernes,18]).
partido([[arsenal,man_united],7,sabado,20]).
partido([[tottenham,man_city],7,sabado,15]).
partido([[newcastle,everton],7,viernes,16]).
partido([[southampton,fulham],13,domingo,15]).
partido([[liverpool,bournemouth],13,sabado,21]).
partido([[brentford,tottenham],13,sabado,18]).
partido([[wolves,nottm_forest],13,domingo,22]).
partido([[leicester_city,brighton],13,domingo,19]).
partido([[crystal_palace,man_city],13,viernes,22]).
partido([[newcastle,leeds_united],13,sabado,14]).
partido([[west_ham,arsenal],13,domingo,18]).
partido([[everton,aston_villa],13,domingo,19]).
partido([[man_united,chelsea],13,sabado,21]).
partido([[leicester_city,aston_villa],3,sabado,22]).
partido([[chelsea,man_city],3,domingo,22]).
partido([[fulham,brighton],3,viernes,16]).
partido([[wolves,leeds_united],3,domingo,21]).
partido([[liverpool,southampton],3,domingo,16]).
partido([[man_united,newcastle],3,domingo,18]).
partido([[nottm_forest,tottenham],3,sabado,19]).
partido([[crystal_palace,west_ham],3,viernes,14]).
partido([[brentford,everton],3,domingo,14]).
partido([[west_ham,brentford],12,domingo,21]).
partido([[crystal_palace,everton],12,viernes,17]).
