partido([[fulham,aston_villa],2,domingo,21]).
partido([[leeds_united,fulham],14,sabado,20]).
partido([[newcastle,man_city],17,domingo,19]).
partido([[newcastle,arsenal],7,sabado,22]).
partido([[chelsea,tottenham],7,viernes,15]).
partido([[southampton,west_ham],7,viernes,22]).
partido([[brentford,fulham],7,sabado,21]).
partido([[wolves,leeds_united],7,viernes,16]).
partido([[aston_villa,leeds_united],18,sabado,14]).
partido([[fulham,crystal_palace],18,viernes,18]).
partido([[nottm_forest,bournemouth],18,viernes,18]).
partido([[chelsea,everton],18,sabado,17]).
partido([[tottenham,arsenal],18,sabado,17]).
partido([[brentford,liverpool],18,viernes,20]).
partido([[newcastle,wolves],18,sabado,14]).
partido([[man_city,man_united],18,domingo,22]).
partido([[southampton,brighton],18,viernes,20]).
partido([[west_ham,leicester_city],18,sabado,15]).
partido([[brighton,leicester_city],4,domingo,20]).
partido([[brentford,crystal_palace],4,sabado,22]).
partido([[brentford,nottm_forest],17,domingo,18]).
partido([[aston_villa,man_united],17,viernes,17]).
partido([[brighton,chelsea],17,domingo,20]).
partido([[leicester_city,wolves],17,sabado,17]).
partido([[bournemouth,southampton],17,sabado,14]).
partido([[everton,leeds_united],17,domingo,16]).
partido([[fulham,west_ham],17,viernes,16]).
partido([[tottenham,liverpool],17,viernes,22]).
partido([[man_united,wolves],16,domingo,20]).
partido([[man_city,crystal_palace],1,domingo,22]).
partido([[man_united,leicester_city],1,viernes,16]).
partido([[tottenham,brighton],1,sabado,21]).
partido([[west_ham,brentford],1,domingo,15]).
partido([[wolves,arsenal],1,viernes,19]).
partido([[aston_villa,chelsea],1,domingo,17]).
partido([[southampton,nottm_forest],1,domingo,16]).
partido([[newcastle,leeds_united],1,sabado,20]).
partido([[everton,fulham],1,viernes,15]).
partido([[liverpool,bournemouth],1,viernes,20]).
partido([[chelsea,brentford],5,viernes,14]).
partido([[brighton,crystal_palace],5,sabado,14]).
partido([[aston_villa,liverpool],5,domingo,14]).
partido([[bournemouth,leeds_united],5,viernes,18]).
partido([[fulham,man_united],5,domingo,21]).
partido([[everton,arsenal],5,sabado,17]).
partido([[wolves,nottm_forest],5,sabado,18]).
partido([[tottenham,west_ham],5,domingo,16]).
partido([[man_city,leicester_city],5,viernes,17]).
partido([[southampton,newcastle],5,domingo,17]).
partido([[brentford,brighton],6,viernes,19]).
partido([[leeds_united,crystal_palace],6,domingo,22]).
partido([[tottenham,nottm_forest],6,viernes,20]).
partido([[newcastle,liverpool],6,sabado,18]).
partido([[man_united,chelsea],6,domingo,15]).
partido([[southampton,fulham],6,sabado,14]).
partido([[aston_villa,arsenal],6,domingo,17]).
partido([[leicester_city,everton],6,viernes,17]).
partido([[arsenal,crystal_palace],17,sabado,20]).
partido([[brighton,newcastle],16,domingo,17]).
partido([[fulham,nottm_forest],16,viernes,18]).
partido([[man_city,wolves],6,viernes,18]).
partido([[bournemouth,west_ham],6,domingo,20]).
partido([[brighton,everton],3,sabado,18]).
partido([[west_ham,man_city],3,viernes,22]).
partido([[man_united,tottenham],3,sabado,14]).
partido([[arsenal,chelsea],3,viernes,20]).
partido([[nottm_forest,aston_villa],3,sabado,21]).
partido([[fulham,leicester_city],3,sabado,22]).
partido([[crystal_palace,southampton],3,domingo,14]).
partido([[leeds_united,liverpool],3,viernes,17]).
partido([[newcastle,brentford],3,sabado,15]).
partido([[wolves,bournemouth],3,viernes,18]).
partido([[arsenal,leicester_city],9,domingo,21]).
partido([[tottenham,leeds_united],9,sabado,17]).
partido([[wolves,crystal_palace],9,sabado,18]).
partido([[nottm_forest,west_ham],9,sabado,22]).
partido([[bournemouth,man_city],9,viernes,19]).
partido([[brentford,everton],9,viernes,20]).
partido([[chelsea,southampton],9,sabado,21]).
partido([[liverpool,man_united],9,viernes,14]).
partido([[brighton,fulham],9,sabado,15]).
partido([[newcastle,aston_villa],9,domingo,16]).
partido([[man_city,brighton],7,viernes,14]).
partido([[everton,liverpool],7,sabado,19]).
partido([[nottm_forest,leicester_city],7,viernes,19]).
partido([[bournemouth,man_united],7,domingo,15]).
partido([[aston_villa,crystal_palace],7,sabado,15]).
partido([[man_city,everton],16,domingo,21]).
partido([[leeds_united,chelsea],16,domingo,14]).
partido([[bournemouth,brentford],16,sabado,19]).
partido([[southampton,arsenal],16,domingo,15]).
partido([[west_ham,aston_villa],16,domingo,18]).
partido([[liverpool,leicester_city],16,sabado,16]).
partido([[tottenham,crystal_palace],16,viernes,21]).
partido([[wolves,everton],13,sabado,22]).
partido([[leeds_united,brighton],13,domingo,21]).
partido([[nottm_forest,chelsea],13,domingo,19]).
partido([[newcastle,man_united],13,domingo,15]).
partido([[man_city,fulham],13,domingo,14]).
partido([[tottenham,leicester_city],13,sabado,18]).
partido([[southampton,liverpool],13,domingo,16]).
partido([[bournemouth,crystal_palace],13,domingo,22]).
partido([[aston_villa,brentford],13,viernes,17]).
partido([[arsenal,west_ham],13,sabado,16]).
partido([[fulham,newcastle],4,viernes,15]).
partido([[nottm_forest,man_united],4,sabado,20]).
partido([[bournemouth,tottenham],4,sabado,21]).
partido([[aston_villa,everton],4,domingo,21]).
partido([[arsenal,leeds_united],4,domingo,21]).
partido([[southampton,wolves],4,viernes,18]).
partido([[chelsea,west_ham],4,domingo,22]).
partido([[man_city,liverpool],4,sabado,20]).
partido([[newcastle,tottenham],14,viernes,18]).
partido([[arsenal,brentford],14,domingo,15]).
partido([[leicester_city,bournemouth],14,sabado,17]).
partido([[brighton,aston_villa],14,sabado,14]).
partido([[man_united,crystal_palace],14,domingo,16]).
partido([[nottm_forest,everton],14,domingo,18]).
partido([[wolves,chelsea],14,domingo,20]).
partido([[man_city,southampton],14,domingo,18]).
partido([[liverpool,west_ham],14,sabado,15]).
partido([[crystal_palace,chelsea],10,domingo,14]).
partido([[wolves,brighton],10,sabado,16]).
partido([[brentford,leicester_city],10,sabado,20]).
partido([[newcastle,west_ham],10,sabado,21]).
partido([[nottm_forest,liverpool],10,viernes,20]).
partido([[tottenham,everton],10,sabado,19]).
partido([[leeds_united,man_city],10,sabado,18]).
partido([[bournemouth,fulham],10,sabado,14]).
partido([[arsenal,man_united],10,viernes,19]).
partido([[aston_villa,southampton],10,sabado,21]).
partido([[southampton,brentford],8,viernes,17]).
partido([[liverpool,arsenal],8,sabado,20]).
partido([[fulham,chelsea],8,sabado,16]).
partido([[tottenham,aston_villa],8,domingo,19]).
partido([[crystal_palace,everton],8,domingo,22]).
partido([[brighton,man_united],8,sabado,17]).
partido([[nottm_forest,man_city],8,domingo,21]).
partido([[wolves,west_ham],8,viernes,21]).
partido([[leicester_city,leeds_united],8,sabado,21]).
partido([[newcastle,bournemouth],8,sabado,18]).
partido([[brentford,wolves],11,sabado,16]).
partido([[man_united,southampton],11,domingo,18]).
partido([[brighton,bournemouth],11,viernes,22]).
partido([[everton,west_ham],11,sabado,17]).
partido([[leicester_city,aston_villa],11,domingo,20]).
partido([[tottenham,fulham],11,viernes,19]).
partido([[leeds_united,nottm_forest],11,domingo,17]).
partido([[liverpool,chelsea],11,viernes,17]).
partido([[arsenal,man_city],11,viernes,14]).
partido([[crystal_palace,newcastle],11,domingo,22]).
partido([[brentford,man_united],12,sabado,16]).
partido([[bournemouth,aston_villa],12,sabado,18]).
partido([[man_city,tottenham],12,sabado,15]).
partido([[leeds_united,west_ham],12,domingo,19]).
partido([[leicester_city,crystal_palace],12,domingo,14]).
partido([[nottm_forest,arsenal],12,domingo,15]).
partido([[everton,southampton],12,domingo,18]).
partido([[newcastle,chelsea],12,domingo,16]).
partido([[liverpool,brighton],12,domingo,22]).
partido([[fulham,wolves],12,sabado,17]).
partido([[wolves,liverpool],2,sabado,16]).
partido([[crystal_palace,west_ham],2,sabado,20]).
partido([[arsenal,brighton],2,viernes,20]).
partido([[tottenham,southampton],2,viernes,19]).
partido([[bournemouth,everton],2,sabado,19]).
partido([[newcastle,nottm_forest],2,domingo,17]).
partido([[man_city,brentford],2,sabado,14]).
partido([[leeds_united,man_united],2,sabado,22]).
partido([[leicester_city,chelsea],2,viernes,16]).
partido([[man_united,west_ham],19,sabado,15]).
partido([[tottenham,wolves],19,viernes,17]).
partido([[liverpool,crystal_palace],19,viernes,15]).
partido([[bournemouth,chelsea],19,domingo,20]).
partido([[arsenal,fulham],19,viernes,22]).
partido([[leeds_united,brentford],19,viernes,20]).
partido([[nottm_forest,brighton],19,domingo,17]).
partido([[everton,newcastle],19,domingo,15]).
partido([[leicester_city,southampton],19,sabado,18]).
partido([[man_city,aston_villa],19,domingo,14]).
partido([[fulham,liverpool],15,viernes,14]).
partido([[wolves,aston_villa],15,sabado,20]).
partido([[crystal_palace,nottm_forest],15,domingo,16]).
partido([[man_city,chelsea],15,viernes,17]).
partido([[southampton,leeds_united],15,viernes,14]).
partido([[everton,man_united],15,domingo,19]).
partido([[bournemouth,arsenal],15,viernes,20]).
partido([[brighton,west_ham],15,viernes,16]).
partido([[leicester_city,newcastle],15,sabado,14]).
partido([[tottenham,brentford],15,sabado,16]).
