partido([[southampton,nottm_forest],17,domingo,21]).
partido([[man_city,man_united],11,domingo,14]).
partido([[west_ham,liverpool],17,sabado,17]).
partido([[fulham,everton],3,domingo,16]).
partido([[aston_villa,west_ham],2,domingo,18]).
partido([[nottm_forest,liverpool],3,sabado,19]).
partido([[man_united,brighton],3,domingo,15]).
partido([[crystal_palace,newcastle],3,viernes,19]).
partido([[wolves,chelsea],3,domingo,22]).
partido([[brentford,west_ham],3,sabado,21]).
partido([[man_city,bournemouth],3,viernes,18]).
partido([[tottenham,southampton],3,viernes,16]).
partido([[leicester_city,bournemouth],2,viernes,17]).
partido([[everton,wolves],2,viernes,18]).
partido([[brentford,newcastle],2,domingo,21]).
partido([[brighton,fulham],2,viernes,19]).
partido([[man_city,arsenal],2,sabado,18]).
partido([[crystal_palace,tottenham],2,sabado,19]).
partido([[liverpool,man_united],2,viernes,14]).
partido([[nottm_forest,chelsea],2,sabado,20]).
partido([[southampton,leeds_united],2,sabado,15]).
partido([[leeds_united,aston_villa],8,sabado,18]).
partido([[wolves,newcastle],8,sabado,18]).
partido([[fulham,nottm_forest],8,domingo,21]).
partido([[brentford,aston_villa],16,domingo,21]).
partido([[southampton,leicester_city],16,domingo,15]).
partido([[fulham,brentford],10,domingo,15]).
partido([[newcastle,man_united],10,viernes,20]).
partido([[leeds_united,brighton],10,sabado,16]).
partido([[crystal_palace,chelsea],10,domingo,18]).
partido([[aston_villa,liverpool],10,domingo,21]).
partido([[tottenham,man_city],10,viernes,16]).
partido([[southampton,bournemouth],10,sabado,19]).
partido([[nottm_forest,west_ham],10,viernes,15]).
partido([[leicester_city,wolves],10,viernes,22]).
partido([[everton,arsenal],10,domingo,19]).
partido([[nottm_forest,aston_villa],11,sabado,22]).
partido([[arsenal,brentford],11,viernes,18]).
partido([[leeds_united,bournemouth],11,viernes,16]).
partido([[fulham,leicester_city],11,sabado,18]).
partido([[leicester_city,leeds_united],3,domingo,20]).
partido([[aston_villa,arsenal],3,viernes,17]).
partido([[tottenham,fulham],7,viernes,19]).
partido([[nottm_forest,newcastle],7,domingo,17]).
partido([[crystal_palace,leeds_united],7,sabado,22]).
partido([[brighton,southampton],7,sabado,20]).
partido([[west_ham,man_united],7,viernes,18]).
partido([[arsenal,leicester_city],7,viernes,15]).
partido([[everton,aston_villa],7,sabado,19]).
partido([[chelsea,liverpool],16,domingo,20]).
partido([[bournemouth,nottm_forest],16,domingo,18]).
partido([[liverpool,crystal_palace],8,sabado,18]).
partido([[west_ham,arsenal],8,sabado,19]).
partido([[bournemouth,tottenham],8,domingo,21]).
partido([[brentford,brighton],8,sabado,15]).
partido([[everton,chelsea],8,sabado,14]).
partido([[leicester_city,man_city],8,domingo,18]).
partido([[man_united,southampton],8,sabado,18]).
partido([[wolves,aston_villa],17,domingo,16]).
partido([[fulham,newcastle],17,sabado,21]).
partido([[leicester_city,man_united],17,sabado,20]).
partido([[arsenal,bournemouth],17,sabado,18]).
partido([[newcastle,chelsea],11,viernes,14]).
partido([[brighton,tottenham],11,domingo,17]).
partido([[crystal_palace,wolves],11,sabado,20]).
partido([[everton,liverpool],11,viernes,17]).
partido([[southampton,west_ham],11,sabado,15]).
partido([[man_city,newcastle],12,sabado,16]).
partido([[chelsea,bournemouth],12,domingo,22]).
partido([[fulham,liverpool],12,sabado,19]).
partido([[tottenham,leeds_united],12,domingo,20]).
partido([[aston_villa,brighton],12,domingo,15]).
partido([[brentford,southampton],12,domingo,19]).
partido([[wolves,nottm_forest],12,viernes,19]).
partido([[crystal_palace,everton],12,sabado,15]).
partido([[man_united,arsenal],12,domingo,21]).
partido([[leicester_city,west_ham],12,viernes,21]).
partido([[man_city,nottm_forest],5,sabado,21]).
partido([[tottenham,aston_villa],5,domingo,17]).
partido([[newcastle,leicester_city],5,sabado,19]).
partido([[everton,southampton],5,sabado,16]).
partido([[west_ham,chelsea],5,sabado,21]).
partido([[tottenham,nottm_forest],6,sabado,16]).
partido([[crystal_palace,west_ham],6,domingo,21]).
partido([[man_city,fulham],6,sabado,20]).
partido([[bournemouth,everton],6,sabado,17]).
partido([[brentford,wolves],6,sabado,22]).
partido([[arsenal,brighton],6,domingo,14]).
partido([[leeds_united,newcastle],6,domingo,22]).
partido([[man_united,aston_villa],6,viernes,22]).
partido([[liverpool,southampton],6,viernes,17]).
partido([[leicester_city,chelsea],6,sabado,15]).
partido([[southampton,chelsea],14,viernes,22]).
partido([[aston_villa,man_city],14,domingo,14]).
partido([[west_ham,fulham],14,domingo,18]).
partido([[arsenal,newcastle],14,sabado,17]).
partido([[liverpool,leeds_united],14,sabado,19]).
partido([[everton,nottm_forest],14,sabado,16]).
partido([[brighton,leicester_city],14,domingo,21]).
partido([[tottenham,wolves],14,viernes,18]).
partido([[bournemouth,crystal_palace],14,sabado,22]).
partido([[man_united,brentford],14,domingo,20]).
partido([[bournemouth,man_united],5,domingo,21]).
partido([[fulham,crystal_palace],5,sabado,22]).
partido([[wolves,brighton],5,sabado,14]).
partido([[brentford,leeds_united],5,viernes,17]).
partido([[liverpool,arsenal],5,sabado,18]).
partido([[man_city,chelsea],7,domingo,19]).
partido([[brentford,bournemouth],7,sabado,15]).
partido([[liverpool,wolves],7,domingo,15]).
partido([[everton,brentford],1,sabado,21]).
partido([[tottenham,arsenal],1,viernes,14]).
partido([[crystal_palace,aston_villa],1,sabado,19]).
partido([[man_united,chelsea],1,domingo,17]).
partido([[leicester_city,liverpool],1,sabado,20]).
partido([[man_city,west_ham],1,viernes,21]).
partido([[newcastle,bournemouth],1,viernes,16]).
partido([[nottm_forest,brighton],1,domingo,21]).
partido([[fulham,leeds_united],1,domingo,18]).
partido([[southampton,wolves],1,sabado,17]).
partido([[leeds_united,arsenal],16,sabado,17]).
partido([[newcastle,everton],16,viernes,19]).
partido([[tottenham,west_ham],16,domingo,16]).
partido([[crystal_palace,brighton],16,domingo,22]).
partido([[man_united,fulham],16,sabado,14]).
partido([[man_city,wolves],16,viernes,16]).
partido([[everton,man_city],19,sabado,21]).
partido([[west_ham,leeds_united],19,viernes,19]).
partido([[arsenal,wolves],19,sabado,17]).
partido([[nottm_forest,man_united],19,domingo,15]).
partido([[southampton,newcastle],19,domingo,21]).
partido([[brighton,bournemouth],19,domingo,20]).
partido([[fulham,aston_villa],19,domingo,19]).
partido([[chelsea,tottenham],19,sabado,14]).
partido([[liverpool,brentford],19,viernes,17]).
partido([[leicester_city,crystal_palace],19,domingo,17]).
partido([[west_ham,brighton],4,sabado,15]).
partido([[southampton,man_city],4,sabado,20]).
partido([[man_united,leeds_united],4,sabado,18]).
partido([[wolves,bournemouth],4,domingo,14]).
partido([[nottm_forest,arsenal],4,sabado,17]).
partido([[crystal_palace,brentford],4,viernes,20]).
partido([[fulham,chelsea],4,sabado,16]).
partido([[tottenham,liverpool],4,domingo,16]).
partido([[leicester_city,everton],4,viernes,16]).
partido([[newcastle,aston_villa],4,viernes,17]).
partido([[newcastle,brighton],9,domingo,15]).
partido([[chelsea,brentford],9,sabado,17]).
partido([[aston_villa,southampton],9,sabado,14]).
partido([[nottm_forest,leicester_city],9,viernes,22]).
partido([[tottenham,man_united],9,domingo,20]).
partido([[west_ham,wolves],9,domingo,17]).
partido([[everton,leeds_united],9,domingo,19]).
partido([[bournemouth,fulham],9,sabado,22]).
partido([[crystal_palace,arsenal],9,domingo,17]).
partido([[liverpool,man_city],9,sabado,14]).
partido([[newcastle,liverpool],15,sabado,18]).
partido([[leicester_city,tottenham],15,domingo,22]).
partido([[aston_villa,bournemouth],15,domingo,21]).
partido([[nottm_forest,brentford],15,sabado,14]).
partido([[man_city,brighton],15,domingo,18]).
partido([[wolves,leeds_united],15,viernes,16]).
partido([[arsenal,chelsea],15,sabado,17]).
partido([[crystal_palace,man_united],15,domingo,14]).
partido([[west_ham,everton],15,sabado,14]).
partido([[fulham,southampton],15,viernes,16]).
partido([[nottm_forest,crystal_palace],18,domingo,17]).
partido([[man_city,leeds_united],18,domingo,19]).
partido([[wolves,fulham],18,viernes,21]).
partido([[tottenham,newcastle],18,sabado,17]).
partido([[chelsea,aston_villa],18,domingo,21]).
partido([[west_ham,bournemouth],18,domingo,20]).
partido([[southampton,arsenal],18,domingo,18]).
partido([[brentford,leicester_city],18,sabado,16]).
partido([[everton,man_united],18,sabado,15]).
partido([[liverpool,brighton],18,viernes,19]).
partido([[west_ham,newcastle],13,viernes,20]).
partido([[man_united,wolves],13,domingo,15]).
partido([[leicester_city,aston_villa],13,domingo,16]).
partido([[arsenal,fulham],13,viernes,18]).
partido([[bournemouth,liverpool],13,sabado,14]).
partido([[leeds_united,nottm_forest],13,domingo,19]).
partido([[man_city,brentford],13,domingo,21]).
partido([[tottenham,everton],13,domingo,17]).
partido([[crystal_palace,southampton],13,sabado,21]).
partido([[brighton,chelsea],13,domingo,22]).
partido([[tottenham,brentford],17,sabado,14]).
partido([[crystal_palace,man_city],17,domingo,15]).
partido([[leeds_united,chelsea],17,domingo,22]).
partido([[brighton,everton],17,viernes,19]).
