partido([[chelsea,west_ham],4,sabado,22]).
partido([[brighton,newcastle],1,domingo,19]).
partido([[leicester_city,west_ham],17,viernes,22]).
partido([[bournemouth,nottm_forest],8,domingo,18]).
partido([[west_ham,tottenham],8,sabado,16]).
partido([[crystal_palace,wolves],8,domingo,21]).
partido([[fulham,liverpool],8,viernes,22]).
partido([[man_united,newcastle],8,domingo,22]).
partido([[chelsea,man_city],8,sabado,21]).
partido([[liverpool,man_city],18,viernes,21]).
partido([[crystal_palace,southampton],18,sabado,17]).
partido([[fulham,arsenal],18,sabado,20]).
partido([[everton,nottm_forest],18,sabado,14]).
partido([[brentford,newcastle],18,viernes,16]).
partido([[tottenham,bournemouth],18,sabado,21]).
partido([[aston_villa,wolves],18,sabado,16]).
partido([[man_united,leicester_city],18,domingo,15]).
partido([[brighton,aston_villa],8,domingo,17]).
partido([[brentford,arsenal],8,viernes,14]).
partido([[leicester_city,everton],8,domingo,14]).
partido([[leeds_united,southampton],8,sabado,22]).
partido([[west_ham,leeds_united],18,domingo,14]).
partido([[brighton,chelsea],18,viernes,15]).
partido([[brighton,man_united],11,viernes,15]).
partido([[newcastle,bournemouth],11,domingo,15]).
partido([[tottenham,wolves],11,domingo,19]).
partido([[fulham,man_city],11,domingo,14]).
partido([[aston_villa,leicester_city],11,viernes,21]).
partido([[chelsea,crystal_palace],11,sabado,22]).
partido([[arsenal,nottm_forest],11,sabado,16]).
partido([[leeds_united,everton],11,domingo,20]).
partido([[southampton,west_ham],11,viernes,16]).
partido([[liverpool,brentford],11,domingo,22]).
partido([[brentford,tottenham],15,viernes,15]).
partido([[west_ham,everton],15,viernes,17]).
partido([[arsenal,brighton],15,domingo,19]).
partido([[newcastle,chelsea],15,sabado,20]).
partido([[southampton,aston_villa],15,viernes,16]).
partido([[wolves,nottm_forest],15,sabado,17]).
partido([[man_united,fulham],15,domingo,18]).
partido([[leeds_united,man_city],15,sabado,18]).
partido([[crystal_palace,liverpool],15,viernes,20]).
partido([[leicester_city,bournemouth],15,domingo,14]).
partido([[leicester_city,arsenal],1,viernes,20]).
partido([[aston_villa,newcastle],17,domingo,21]).
partido([[southampton,wolves],17,sabado,17]).
partido([[man_united,crystal_palace],17,domingo,22]).
partido([[brentford,everton],17,viernes,19]).
partido([[leeds_united,tottenham],17,viernes,20]).
partido([[chelsea,fulham],17,domingo,18]).
partido([[man_city,nottm_forest],17,sabado,19]).
partido([[arsenal,liverpool],17,sabado,22]).
partido([[brighton,bournemouth],17,domingo,19]).
partido([[bournemouth,everton],1,sabado,21]).
partido([[leicester_city,chelsea],13,sabado,22]).
partido([[wolves,brentford],13,domingo,18]).
partido([[fulham,crystal_palace],13,sabado,14]).
partido([[nottm_forest,liverpool],13,domingo,17]).
partido([[wolves,liverpool],9,domingo,16]).
partido([[chelsea,nottm_forest],9,domingo,17]).
partido([[brentford,crystal_palace],9,sabado,20]).
partido([[fulham,leicester_city],9,viernes,22]).
partido([[man_city,man_united],9,viernes,19]).
partido([[southampton,everton],9,sabado,20]).
partido([[west_ham,newcastle],9,sabado,19]).
partido([[brighton,tottenham],9,domingo,14]).
partido([[arsenal,aston_villa],9,sabado,18]).
partido([[leeds_united,bournemouth],9,sabado,16]).
partido([[man_city,everton],13,domingo,17]).
partido([[man_united,tottenham],13,domingo,22]).
partido([[arsenal,west_ham],13,sabado,15]).
partido([[leeds_united,brighton],13,domingo,14]).
partido([[newcastle,southampton],13,domingo,18]).
partido([[aston_villa,bournemouth],13,sabado,19]).
partido([[crystal_palace,man_city],1,sabado,17]).
partido([[brentford,southampton],1,sabado,17]).
partido([[west_ham,fulham],1,sabado,14]).
partido([[liverpool,man_united],1,sabado,15]).
partido([[chelsea,tottenham],1,domingo,21]).
partido([[wolves,leeds_united],1,viernes,22]).
partido([[nottm_forest,aston_villa],1,domingo,20]).
partido([[tottenham,newcastle],10,viernes,22]).
partido([[leeds_united,fulham],10,sabado,17]).
partido([[aston_villa,chelsea],10,sabado,22]).
partido([[leicester_city,man_city],10,domingo,21]).
partido([[liverpool,bournemouth],10,domingo,16]).
partido([[man_united,brentford],10,viernes,16]).
partido([[southampton,nottm_forest],10,sabado,19]).
partido([[wolves,arsenal],10,viernes,19]).
partido([[brighton,everton],10,sabado,18]).
partido([[west_ham,crystal_palace],10,domingo,17]).
partido([[bournemouth,chelsea],12,domingo,20]).
partido([[aston_villa,man_united],12,viernes,18]).
partido([[liverpool,west_ham],12,sabado,18]).
partido([[wolves,everton],12,viernes,17]).
partido([[newcastle,fulham],12,sabado,15]).
partido([[arsenal,leeds_united],12,sabado,21]).
partido([[leicester_city,crystal_palace],12,domingo,15]).
partido([[tottenham,nottm_forest],12,sabado,17]).
partido([[brighton,southampton],12,sabado,16]).
partido([[brentford,man_city],12,sabado,14]).
partido([[brentford,bournemouth],5,domingo,15]).
partido([[liverpool,tottenham],5,domingo,18]).
partido([[man_city,aston_villa],5,domingo,17]).
partido([[leicester_city,newcastle],5,domingo,18]).
partido([[leeds_united,man_united],5,domingo,20]).
partido([[west_ham,brighton],5,domingo,21]).
partido([[wolves,chelsea],5,domingo,17]).
partido([[southampton,arsenal],5,domingo,14]).
partido([[fulham,everton],5,domingo,22]).
partido([[nottm_forest,crystal_palace],5,viernes,14]).
partido([[bournemouth,man_united],4,viernes,18]).
partido([[leeds_united,brentford],4,domingo,22]).
partido([[crystal_palace,brighton],4,domingo,19]).
partido([[arsenal,newcastle],4,domingo,17]).
partido([[leicester_city,liverpool],4,viernes,17]).
partido([[man_city,wolves],4,viernes,16]).
partido([[southampton,tottenham],4,sabado,17]).
partido([[nottm_forest,fulham],4,domingo,15]).
partido([[aston_villa,everton],4,domingo,21]).
partido([[newcastle,leeds_united],14,sabado,18]).
partido([[arsenal,crystal_palace],14,domingo,18]).
partido([[nottm_forest,man_united],14,viernes,16]).
partido([[wolves,bournemouth],14,viernes,21]).
partido([[west_ham,man_city],14,sabado,20]).
partido([[aston_villa,brentford],14,domingo,16]).
partido([[southampton,liverpool],14,viernes,15]).
partido([[tottenham,leicester_city],14,viernes,17]).
partido([[chelsea,everton],14,sabado,14]).
partido([[brighton,fulham],14,sabado,21]).
partido([[man_city,arsenal],6,domingo,14]).
partido([[man_united,everton],6,domingo,21]).
partido([[leeds_united,chelsea],6,domingo,15]).
partido([[leicester_city,southampton],6,sabado,18]).
partido([[nottm_forest,brighton],6,domingo,16]).
partido([[bournemouth,crystal_palace],6,domingo,19]).
partido([[brentford,west_ham],6,domingo,17]).
partido([[newcastle,wolves],6,sabado,15]).
partido([[fulham,tottenham],6,viernes,20]).
partido([[aston_villa,liverpool],6,viernes,15]).
partido([[brighton,brentford],2,domingo,16]).
partido([[leeds_united,crystal_palace],2,viernes,18]).
partido([[leicester_city,nottm_forest],2,viernes,14]).
partido([[bournemouth,man_city],2,domingo,17]).
partido([[everton,arsenal],2,viernes,22]).
partido([[chelsea,southampton],2,domingo,22]).
partido([[tottenham,aston_villa],2,sabado,20]).
partido([[wolves,fulham],2,domingo,15]).
partido([[newcastle,liverpool],2,domingo,21]).
partido([[man_united,west_ham],2,domingo,19]).
partido([[leicester_city,leeds_united],19,sabado,20]).
partido([[liverpool,brighton],19,viernes,19]).
partido([[brentford,leicester_city],3,domingo,14]).
partido([[man_city,newcastle],3,sabado,21]).
partido([[crystal_palace,tottenham],3,domingo,19]).
partido([[wolves,brighton],3,sabado,15]).
partido([[liverpool,everton],3,domingo,19]).
partido([[leeds_united,aston_villa],3,domingo,18]).
partido([[west_ham,nottm_forest],3,domingo,18]).
partido([[man_united,southampton],3,sabado,17]).
partido([[bournemouth,fulham],3,sabado,14]).
partido([[chelsea,arsenal],3,domingo,18]).
partido([[bournemouth,southampton],7,sabado,21]).
partido([[brentford,fulham],7,viernes,15]).
partido([[west_ham,aston_villa],7,viernes,14]).
partido([[chelsea,liverpool],7,sabado,22]).
partido([[brighton,man_city],7,sabado,14]).
partido([[leeds_united,nottm_forest],7,sabado,19]).
partido([[tottenham,everton],7,viernes,17]).
partido([[newcastle,crystal_palace],7,viernes,19]).
partido([[arsenal,man_united],7,viernes,20]).
partido([[leicester_city,wolves],7,viernes,18]).
partido([[leicester_city,brighton],16,sabado,20]).
partido([[leeds_united,liverpool],16,sabado,14]).
partido([[newcastle,everton],19,sabado,18]).
partido([[bournemouth,arsenal],19,domingo,21]).
partido([[tottenham,man_city],19,domingo,20]).
partido([[west_ham,wolves],19,sabado,21]).
partido([[crystal_palace,aston_villa],19,viernes,20]).
partido([[southampton,fulham],19,domingo,15]).
partido([[chelsea,man_united],19,sabado,18]).
partido([[brentford,nottm_forest],19,domingo,15]).
partido([[southampton,man_city],16,viernes,22]).
partido([[newcastle,nottm_forest],16,sabado,19]).
partido([[man_united,wolves],16,viernes,16]).
partido([[chelsea,brentford],16,viernes,15]).
partido([[bournemouth,west_ham],16,domingo,19]).
partido([[aston_villa,fulham],16,viernes,14]).
partido([[crystal_palace,everton],16,viernes,19]).
partido([[arsenal,tottenham],16,sabado,17]).
