partido([[southampton,newcastle],12,domingo,21]).
partido([[west_ham,tottenham],12,viernes,15]).
partido([[bournemouth,newcastle],4,viernes,19]).
partido([[leeds_united,crystal_palace],7,viernes,15]).
partido([[leicester_city,man_united],7,sabado,21]).
partido([[wolves,man_city],7,sabado,16]).
partido([[tottenham,newcastle],7,domingo,16]).
partido([[everton,aston_villa],7,viernes,16]).
partido([[brentford,liverpool],7,viernes,17]).
partido([[southampton,brighton],7,viernes,14]).
partido([[arsenal,fulham],7,domingo,22]).
partido([[chelsea,bournemouth],7,domingo,21]).
partido([[nottm_forest,west_ham],7,viernes,18]).
partido([[newcastle,wolves],5,domingo,16]).
partido([[man_city,brighton],5,domingo,20]).
partido([[liverpool,nottm_forest],5,sabado,19]).
partido([[aston_villa,tottenham],5,viernes,21]).
partido([[everton,arsenal],5,sabado,14]).
partido([[man_united,brentford],5,viernes,18]).
partido([[leicester_city,west_ham],5,domingo,19]).
partido([[fulham,bournemouth],5,viernes,17]).
partido([[crystal_palace,southampton],5,domingo,18]).
partido([[chelsea,leeds_united],5,domingo,14]).
partido([[liverpool,leicester_city],18,sabado,17]).
partido([[fulham,newcastle],13,domingo,20]).
partido([[nottm_forest,leeds_united],13,sabado,15]).
partido([[man_united,chelsea],13,sabado,21]).
partido([[everton,brighton],13,viernes,16]).
partido([[bournemouth,brentford],13,sabado,16]).
partido([[liverpool,southampton],13,domingo,17]).
partido([[west_ham,wolves],13,domingo,14]).
partido([[tottenham,man_city],13,sabado,21]).
partido([[arsenal,man_city],14,sabado,15]).
partido([[leicester_city,bournemouth],14,viernes,20]).
partido([[west_ham,crystal_palace],8,domingo,17]).
partido([[chelsea,man_city],8,domingo,19]).
partido([[nottm_forest,everton],8,viernes,15]).
partido([[man_united,southampton],8,viernes,16]).
partido([[wolves,tottenham],8,viernes,17]).
partido([[leicester_city,brentford],8,domingo,18]).
partido([[newcastle,aston_villa],8,viernes,21]).
partido([[leeds_united,liverpool],8,domingo,22]).
partido([[brighton,fulham],8,viernes,19]).
partido([[arsenal,bournemouth],8,viernes,22]).
partido([[arsenal,crystal_palace],18,domingo,16]).
partido([[man_city,fulham],18,sabado,18]).
partido([[brentford,wolves],18,domingo,19]).
partido([[tottenham,everton],18,domingo,14]).
partido([[leeds_united,southampton],18,sabado,19]).
partido([[brighton,newcastle],18,sabado,20]).
partido([[aston_villa,bournemouth],18,sabado,17]).
partido([[nottm_forest,chelsea],18,domingo,14]).
partido([[west_ham,man_united],18,sabado,18]).
partido([[wolves,aston_villa],17,viernes,15]).
partido([[brentford,newcastle],17,viernes,18]).
partido([[everton,leicester_city],17,viernes,19]).
partido([[crystal_palace,brighton],17,viernes,17]).
partido([[man_city,west_ham],17,viernes,16]).
partido([[leeds_united,man_united],17,domingo,20]).
partido([[fulham,liverpool],17,sabado,20]).
partido([[chelsea,arsenal],17,domingo,19]).
partido([[tottenham,nottm_forest],17,viernes,14]).
partido([[bournemouth,southampton],17,domingo,15]).
partido([[newcastle,leeds_united],6,sabado,17]).
partido([[chelsea,brentford],6,sabado,16]).
partido([[west_ham,brighton],6,sabado,22]).
partido([[southampton,tottenham],6,domingo,20]).
partido([[wolves,southampton],10,viernes,20]).
partido([[tottenham,crystal_palace],10,sabado,14]).
partido([[everton,man_united],10,viernes,18]).
partido([[nottm_forest,man_city],10,domingo,14]).
partido([[leeds_united,bournemouth],10,viernes,19]).
partido([[brighton,brentford],10,viernes,15]).
partido([[aston_villa,leicester_city],10,domingo,16]).
partido([[arsenal,newcastle],10,domingo,18]).
partido([[fulham,chelsea],10,domingo,22]).
partido([[west_ham,liverpool],10,domingo,19]).
partido([[west_ham,southampton],16,viernes,21]).
partido([[tottenham,brighton],16,domingo,21]).
partido([[man_city,leeds_united],16,viernes,15]).
partido([[everton,brentford],16,viernes,14]).
partido([[arsenal,nottm_forest],16,domingo,20]).
partido([[bournemouth,man_united],16,domingo,15]).
partido([[liverpool,aston_villa],16,sabado,17]).
partido([[crystal_palace,fulham],16,sabado,22]).
partido([[wolves,leicester_city],16,sabado,18]).
partido([[chelsea,newcastle],16,sabado,15]).
partido([[man_city,southampton],2,viernes,18]).
partido([[everton,fulham],2,viernes,20]).
partido([[nottm_forest,leicester_city],2,domingo,21]).
partido([[newcastle,man_united],2,sabado,18]).
partido([[west_ham,arsenal],2,domingo,19]).
partido([[chelsea,aston_villa],2,domingo,14]).
partido([[brentford,crystal_palace],2,sabado,21]).
partido([[brighton,leeds_united],2,sabado,22]).
partido([[bournemouth,tottenham],2,domingo,15]).
partido([[wolves,liverpool],2,sabado,15]).
partido([[west_ham,chelsea],11,viernes,21]).
partido([[southampton,aston_villa],11,domingo,16]).
partido([[nottm_forest,brentford],11,sabado,18]).
partido([[wolves,bournemouth],11,domingo,19]).
partido([[everton,newcastle],11,domingo,20]).
partido([[arsenal,leeds_united],11,viernes,15]).
partido([[crystal_palace,liverpool],11,viernes,16]).
partido([[brighton,leicester_city],11,viernes,22]).
partido([[tottenham,fulham],11,domingo,14]).
partido([[man_united,man_city],11,sabado,20]).
partido([[west_ham,everton],3,sabado,17]).
partido([[brentford,fulham],3,domingo,20]).
partido([[nottm_forest,aston_villa],3,sabado,17]).
partido([[newcastle,leicester_city],3,domingo,19]).
partido([[chelsea,crystal_palace],3,domingo,20]).
partido([[tottenham,leeds_united],3,sabado,15]).
partido([[bournemouth,brighton],3,sabado,19]).
partido([[liverpool,man_city],3,sabado,16]).
partido([[southampton,arsenal],3,viernes,21]).
partido([[man_united,wolves],3,domingo,18]).
partido([[crystal_palace,leicester_city],13,sabado,20]).
partido([[aston_villa,arsenal],13,viernes,16]).
partido([[aston_villa,man_united],15,sabado,14]).
partido([[brighton,arsenal],15,domingo,15]).
partido([[brentford,west_ham],15,domingo,16]).
partido([[everton,bournemouth],15,sabado,22]).
partido([[leicester_city,leeds_united],15,sabado,21]).
partido([[newcastle,nottm_forest],15,sabado,20]).
partido([[fulham,wolves],15,domingo,22]).
partido([[chelsea,southampton],15,sabado,14]).
partido([[liverpool,tottenham],15,sabado,15]).
partido([[crystal_palace,man_city],15,domingo,22]).
partido([[brighton,liverpool],4,viernes,22]).
partido([[everton,chelsea],4,domingo,19]).
partido([[west_ham,leeds_united],4,sabado,14]).
partido([[man_united,nottm_forest],4,sabado,18]).
partido([[fulham,southampton],4,sabado,15]).
partido([[brentford,tottenham],4,domingo,18]).
partido([[crystal_palace,aston_villa],4,sabado,17]).
partido([[arsenal,wolves],4,domingo,20]).
partido([[leicester_city,man_city],4,sabado,22]).
partido([[leicester_city,southampton],19,domingo,16]).
partido([[nottm_forest,fulham],19,sabado,16]).
partido([[man_united,brighton],19,domingo,18]).
partido([[crystal_palace,newcastle],19,viernes,20]).
partido([[bournemouth,west_ham],19,domingo,22]).
partido([[chelsea,liverpool],19,domingo,21]).
partido([[tottenham,arsenal],19,domingo,19]).
partido([[man_united,fulham],14,viernes,19]).
partido([[chelsea,tottenham],14,sabado,17]).
partido([[west_ham,aston_villa],14,domingo,22]).
partido([[everton,leeds_united],14,sabado,14]).
partido([[brentford,southampton],14,viernes,14]).
partido([[nottm_forest,crystal_palace],14,domingo,21]).
partido([[wolves,brighton],14,domingo,21]).
partido([[liverpool,newcastle],14,domingo,21]).
partido([[crystal_palace,wolves],9,domingo,17]).
partido([[man_city,newcastle],9,domingo,16]).
partido([[man_united,tottenham],9,viernes,17]).
partido([[everton,southampton],9,domingo,22]).
partido([[arsenal,brentford],9,viernes,21]).
partido([[chelsea,leicester_city],9,sabado,17]).
partido([[bournemouth,liverpool],9,viernes,14]).
partido([[fulham,west_ham],9,domingo,21]).
partido([[leeds_united,aston_villa],9,sabado,19]).
partido([[nottm_forest,brighton],9,sabado,21]).
partido([[west_ham,newcastle],1,viernes,17]).
partido([[arsenal,man_united],1,sabado,21]).
partido([[brentford,man_city],1,sabado,16]).
partido([[everton,liverpool],1,domingo,15]).
partido([[nottm_forest,southampton],1,sabado,16]).
partido([[brighton,aston_villa],1,domingo,22]).
partido([[fulham,leeds_united],1,domingo,20]).
partido([[wolves,chelsea],1,viernes,15]).
partido([[bournemouth,crystal_palace],1,sabado,21]).
partido([[leicester_city,tottenham],1,viernes,21]).
partido([[brighton,chelsea],12,viernes,19]).
partido([[bournemouth,nottm_forest],12,sabado,19]).
partido([[leicester_city,fulham],12,viernes,16]).
partido([[arsenal,liverpool],12,domingo,15]).
partido([[man_united,crystal_palace],12,sabado,20]).
partido([[wolves,nottm_forest],6,viernes,19]).
partido([[bournemouth,man_city],6,sabado,20]).
partido([[leicester_city,arsenal],6,viernes,17]).
partido([[aston_villa,fulham],6,domingo,14]).
partido([[man_united,liverpool],6,viernes,21]).
partido([[everton,crystal_palace],6,viernes,15]).
partido([[everton,man_city],12,sabado,17]).
partido([[leeds_united,wolves],12,domingo,17]).
partido([[brentford,aston_villa],12,sabado,16]).
partido([[brentford,leeds_united],19,sabado,14]).
partido([[wolves,everton],19,domingo,17]).
partido([[aston_villa,man_city],19,viernes,19]).
