partido([[aston_villa,west_ham],2,sabado,20]).
partido([[southampton,arsenal],11,sabado,19]).
partido([[fulham,chelsea],18,viernes,20]).
partido([[wolves,bournemouth],19,sabado,21]).
partido([[liverpool,everton],3,domingo,21]).
partido([[tottenham,bournemouth],14,domingo,16]).
partido([[southampton,brentford],5,domingo,22]).
partido([[brighton,man_united],1,domingo,16]).
partido([[tottenham,west_ham],1,viernes,20]).
partido([[southampton,wolves],13,domingo,20]).
partido([[liverpool,leeds_united],13,domingo,17]).
partido([[nottm_forest,aston_villa],13,sabado,20]).
partido([[chelsea,bournemouth],13,viernes,16]).
partido([[fulham,everton],13,domingo,19]).
partido([[brighton,crystal_palace],13,domingo,21]).
partido([[brentford,tottenham],13,viernes,17]).
partido([[arsenal,man_united],13,viernes,21]).
partido([[newcastle,west_ham],13,viernes,18]).
partido([[man_city,leicester_city],13,sabado,14]).
partido([[man_united,chelsea],10,domingo,22]).
partido([[west_ham,man_united],15,domingo,17]).
partido([[arsenal,leicester_city],5,viernes,20]).
partido([[crystal_palace,tottenham],10,sabado,21]).
partido([[man_city,newcastle],10,domingo,19]).
partido([[everton,southampton],10,domingo,14]).
partido([[bournemouth,arsenal],10,domingo,15]).
partido([[brentford,liverpool],10,domingo,17]).
partido([[nottm_forest,brighton],10,sabado,18]).
partido([[fulham,leicester_city],10,viernes,19]).
partido([[leeds_united,aston_villa],10,domingo,20]).
partido([[west_ham,wolves],10,sabado,14]).
partido([[everton,chelsea],5,viernes,15]).
partido([[liverpool,brighton],5,viernes,21]).
partido([[man_united,bournemouth],5,domingo,21]).
partido([[tottenham,nottm_forest],5,viernes,16]).
partido([[crystal_palace,fulham],5,domingo,14]).
partido([[west_ham,leeds_united],5,sabado,15]).
partido([[man_city,aston_villa],5,domingo,18]).
partido([[newcastle,wolves],5,viernes,14]).
partido([[brighton,tottenham],15,sabado,16]).
partido([[man_united,crystal_palace],4,viernes,22]).
partido([[brighton,man_city],4,sabado,22]).
partido([[bournemouth,liverpool],4,domingo,19]).
partido([[leeds_united,leicester_city],4,viernes,14]).
partido([[tottenham,everton],4,viernes,16]).
partido([[wolves,fulham],4,domingo,21]).
partido([[nottm_forest,west_ham],4,sabado,15]).
partido([[arsenal,aston_villa],4,domingo,18]).
partido([[southampton,chelsea],4,domingo,17]).
partido([[brentford,newcastle],4,viernes,21]).
partido([[west_ham,chelsea],17,domingo,15]).
partido([[brentford,leeds_united],17,sabado,17]).
partido([[liverpool,man_united],17,viernes,21]).
partido([[southampton,brighton],17,domingo,21]).
partido([[bournemouth,leicester_city],17,domingo,16]).
partido([[nottm_forest,everton],17,sabado,16]).
partido([[man_city,arsenal],17,sabado,14]).
partido([[crystal_palace,wolves],17,domingo,22]).
partido([[liverpool,nottm_forest],9,domingo,16]).
partido([[man_united,leicester_city],9,domingo,15]).
partido([[everton,west_ham],9,domingo,17]).
partido([[bournemouth,southampton],9,sabado,16]).
partido([[aston_villa,crystal_palace],9,viernes,21]).
partido([[chelsea,newcastle],9,sabado,19]).
partido([[tottenham,wolves],9,sabado,18]).
partido([[brentford,fulham],9,sabado,16]).
partido([[man_city,leeds_united],9,domingo,15]).
partido([[brighton,arsenal],9,domingo,16]).
partido([[southampton,nottm_forest],7,sabado,16]).
partido([[chelsea,brentford],7,viernes,17]).
partido([[west_ham,arsenal],7,viernes,19]).
partido([[everton,crystal_palace],12,viernes,14]).
partido([[man_city,nottm_forest],12,domingo,19]).
partido([[leicester_city,liverpool],12,viernes,16]).
partido([[brighton,aston_villa],12,sabado,21]).
partido([[man_united,brentford],12,viernes,18]).
partido([[west_ham,bournemouth],12,domingo,16]).
partido([[arsenal,wolves],12,domingo,14]).
partido([[fulham,tottenham],12,domingo,17]).
partido([[leeds_united,chelsea],12,sabado,19]).
partido([[newcastle,southampton],12,sabado,18]).
partido([[southampton,west_ham],14,sabado,22]).
partido([[aston_villa,everton],14,sabado,21]).
partido([[nottm_forest,brentford],14,viernes,21]).
partido([[leicester_city,brighton],14,viernes,19]).
partido([[liverpool,newcastle],14,sabado,17]).
partido([[leeds_united,arsenal],14,sabado,20]).
partido([[man_united,wolves],14,sabado,16]).
partido([[fulham,man_city],14,domingo,15]).
partido([[crystal_palace,chelsea],14,sabado,14]).
partido([[fulham,nottm_forest],8,sabado,22]).
partido([[west_ham,leicester_city],8,viernes,19]).
partido([[newcastle,brighton],8,domingo,18]).
partido([[brentford,crystal_palace],8,sabado,22]).
partido([[chelsea,man_city],8,viernes,18]).
partido([[liverpool,southampton],8,viernes,14]).
partido([[wolves,leeds_united],8,domingo,19]).
partido([[tottenham,arsenal],8,sabado,20]).
partido([[everton,bournemouth],8,viernes,17]).
partido([[man_united,aston_villa],8,sabado,16]).
partido([[brentford,brighton],3,domingo,14]).
partido([[aston_villa,leicester_city],3,domingo,22]).
partido([[nottm_forest,arsenal],3,viernes,14]).
partido([[chelsea,wolves],3,sabado,15]).
partido([[leeds_united,man_united],3,viernes,19]).
partido([[newcastle,bournemouth],3,domingo,19]).
partido([[crystal_palace,man_city],3,sabado,17]).
partido([[tottenham,southampton],3,viernes,15]).
partido([[fulham,west_ham],3,sabado,19]).
partido([[bournemouth,nottm_forest],6,viernes,19]).
partido([[southampton,leicester_city],6,domingo,15]).
partido([[arsenal,brentford],6,viernes,18]).
partido([[everton,man_city],6,domingo,22]).
partido([[wolves,aston_villa],6,sabado,14]).
partido([[brighton,chelsea],6,viernes,20]).
partido([[fulham,man_united],6,domingo,17]).
partido([[leeds_united,newcastle],6,sabado,19]).
partido([[tottenham,liverpool],6,sabado,17]).
partido([[west_ham,crystal_palace],6,viernes,21]).
partido([[everton,brighton],19,domingo,18]).
partido([[leicester_city,tottenham],19,sabado,17]).
partido([[nottm_forest,man_united],19,domingo,19]).
partido([[crystal_palace,newcastle],19,sabado,17]).
partido([[leeds_united,fulham],19,sabado,21]).
partido([[liverpool,west_ham],19,domingo,15]).
partido([[man_city,southampton],19,viernes,14]).
partido([[arsenal,chelsea],19,viernes,22]).
partido([[brentford,aston_villa],19,sabado,22]).
partido([[brentford,man_city],16,viernes,22]).
partido([[west_ham,brighton],16,sabado,19]).
partido([[nottm_forest,leicester_city],16,viernes,22]).
partido([[wolves,liverpool],16,domingo,16]).
partido([[fulham,bournemouth],16,domingo,17]).
partido([[man_united,newcastle],16,sabado,19]).
partido([[leeds_united,everton],16,domingo,16]).
partido([[crystal_palace,arsenal],16,viernes,19]).
partido([[aston_villa,southampton],16,domingo,15]).
partido([[chelsea,tottenham],16,viernes,16]).
partido([[newcastle,arsenal],18,sabado,14]).
partido([[wolves,everton],18,sabado,20]).
partido([[bournemouth,brighton],18,sabado,22]).
partido([[leicester_city,brentford],18,domingo,17]).
partido([[liverpool,aston_villa],18,sabado,18]).
partido([[man_city,west_ham],18,viernes,19]).
partido([[tottenham,man_united],18,domingo,20]).
partido([[nottm_forest,leeds_united],18,viernes,22]).
partido([[crystal_palace,southampton],18,viernes,17]).
partido([[everton,leicester_city],7,domingo,19]).
partido([[bournemouth,crystal_palace],7,domingo,18]).
partido([[brighton,wolves],7,domingo,22]).
partido([[tottenham,leeds_united],7,sabado,22]).
partido([[fulham,liverpool],7,sabado,22]).
partido([[man_city,man_united],7,sabado,22]).
partido([[aston_villa,newcastle],7,sabado,19]).
partido([[newcastle,everton],2,viernes,14]).
partido([[man_city,tottenham],2,sabado,16]).
partido([[crystal_palace,nottm_forest],2,domingo,19]).
partido([[leeds_united,bournemouth],2,domingo,14]).
partido([[brighton,fulham],2,viernes,15]).
partido([[arsenal,liverpool],2,sabado,17]).
partido([[brentford,wolves],2,domingo,17]).
partido([[southampton,man_united],2,domingo,15]).
partido([[leicester_city,chelsea],2,domingo,16]).
partido([[nottm_forest,chelsea],11,viernes,19]).
partido([[brentford,west_ham],11,sabado,14]).
partido([[everton,man_united],11,viernes,22]).
partido([[wolves,leicester_city],11,domingo,17]).
partido([[brighton,leeds_united],11,domingo,18]).
partido([[liverpool,crystal_palace],11,sabado,22]).
partido([[bournemouth,man_city],11,viernes,21]).
partido([[tottenham,aston_villa],11,sabado,17]).
partido([[newcastle,fulham],11,viernes,14]).
partido([[fulham,aston_villa],17,sabado,22]).
partido([[newcastle,tottenham],17,sabado,18]).
partido([[nottm_forest,newcastle],1,domingo,14]).
partido([[brentford,everton],1,sabado,15]).
partido([[liverpool,chelsea],1,sabado,22]).
partido([[fulham,arsenal],1,sabado,20]).
partido([[bournemouth,aston_villa],1,sabado,16]).
partido([[man_city,wolves],1,viernes,21]).
partido([[leeds_united,southampton],1,domingo,22]).
partido([[crystal_palace,leicester_city],1,domingo,19]).
partido([[leeds_united,crystal_palace],15,domingo,17]).
partido([[chelsea,aston_villa],15,sabado,15]).
partido([[man_city,liverpool],15,sabado,16]).
partido([[everton,arsenal],15,sabado,16]).
partido([[wolves,nottm_forest],15,sabado,17]).
partido([[leicester_city,newcastle],15,domingo,20]).
partido([[fulham,southampton],15,viernes,14]).
partido([[brentford,bournemouth],15,viernes,21]).
